### PR TITLE
Update my name and affiliation

### PR DESCRIPTION
**Pull request by langner**

### CODE REVIEW

**Comment by drvinceknight** [comment]
This is not the correct branch. I'll fix on the `arxiv` branch.

**Comment by drvinceknight** [comment]
Actually, going to fix on a new branch which I'll use to keep track of further amendments which we'll do after peer review.

**Comment by langner** [comment]
Thanks.

**Comment by drvinceknight** [comment]
See: https://github.com/Axelrod-Python/An-open-reproducible-framework-for-the-study-of-the-iterated-prisoners-dilemma/tree/arxiv-rev

**Pull request closed without merging**
