### PR TITLE
Adding references about memory one strategies

### PR DESCRIPTION
**Pull request by drvinceknight**
After discussion on https://github.com/Axelrod-Python/Axelrod/issues/170 I've added these two references about memory one strategies:
- Stewart, Alexander J and Plotkin, Joshua B: Pnas
- Press, William H and Dyson, Freeman J: Pnas

### CODE REVIEW

**Comment by langner** [comment]
Oh, I already added the Freeman & Dyson paper! So I guess we'll be doing PRs here too from now on.

**Comment by langner** [comment]
OK, I reverted so this will go through smoothly.

**Comment by drvinceknight** [comment]
> Oh, I already added the Freeman & Dyson paper! So I guess we'll be doing PRs here too from now on.

Assuming you're happy with that? At some point I guess it would be good to discuss/decide what the paper is about?

**Comment by drvinceknight** [comment]
Have opened #2

**Pull request merged**
